# Generated by Django 3.0.7 on 2022-04-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hashstr',
            field=models.TextField(null=True),
        ),
    ]
