# Generated by Django 3.0.7 on 2022-04-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_hashstr'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verify',
            field=models.IntegerField(default='0'),
        ),
    ]
