# Generated by Django 3.0.7 on 2021-01-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=255, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updatee_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
