# Generated by Django 3.0.7 on 2021-02-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210213_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
