# Generated by Django 3.0.7 on 2021-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_customeraddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address_line1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address_line2',
            field=models.TextField(null=True),
        ),
    ]
