# Generated by Django 3.0.7 on 2021-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210523_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='is_billing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='is_shipping',
            field=models.IntegerField(default=0),
        ),
    ]
