# Generated by Django 3.0.7 on 2021-05-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20210529_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='is_default_shipping',
            field=models.IntegerField(default=0),
        ),
    ]
