# Generated by Django 3.0.7 on 2021-06-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_customeraddress_is_default_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='billing_address_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shipping_address_id',
            field=models.IntegerField(null=True),
        ),
    ]
