# Generated by Django 3.0.7 on 2022-03-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_profile', '0004_groupinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='login_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
